spring:
  application:
    name: server
  datasource:
    url: jdbc:h2:file:./data/addressbookdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
jsonserver:
  base-url: http://localhost:3000/contacts
